runtime: python39
entrypoint: gunicorn -b :$PORT main:app

handlers:
  - url: /(.*\.(html))$
    static_files: views/\1
    upload: views/(.*\.(html))$
    secure: always

  - url: /(.*\.(css))$
    static_files: assets/css/\1
    upload: assets/css/(.*\.(css))$
    secure: always

  - url: /(.*\.(js))$
    static_files: assets/js/\1
    upload: assets/js/(.*\.(js))$
    secure: always

  - url: /.*
    script: auto
